### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by bravuralion** [mikwielgus/forum-dl#20]
When i try to install this with PIP, i get the following Error:

      creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet
      creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet\src
      creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet\src\LangModels
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Isrc/ext/uchardet/src -IC:\Users\set\AppData\Local\Programs\Python\Python311\include -IC:\Users\set\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsrc/cchardet\_cchardet.cpp /Fobuild\temp.win-amd64-cpython-311\Release\src/cchardet\_cchardet.obj
      _cchardet.cpp
      src/cchardet\_cchardet.cpp(196): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "longintrepr.h": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cchardet
Failed to build cchardet
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cchardet)

**Comment by bravuralion** [comment]
ok got it to run with python 3.10, but when starting the tool, i get this:

Traceback (most recent call last):
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\Scripts\forum-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\site-packages\forum_dl\__init__.py", line 34, in main
    forumdl.download(
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\site-packages\forum_dl\forumdl.py", line 24, in download
    self.download_url(
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\site-packages\forum_dl\forumdl.py", line 48, in download_url
    writer.write(url)
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\site-packages\forum_dl\writers\common.py", line 78, in write
    self.write_board(base_node)
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\site-packages\forum_dl\writers\common.py", line 103, in write_board
    self._write_board_object(board)
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\site-packages\forum_dl\writers\common.py", line 235, in _write_board_object
    sys.stdout.write(f"{self._serialize_entry(entry)}\n")
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\site-packages\forum_dl\writers\jsonl.py", line 10, in _serialize_entry
    return entry.json(models_as_dict=False)
  File "C:\Users\set\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\main.py", line 1117, in json
    raise TypeError('The `models_as_dict` argument is no longer supported; use a model serializer instead.')
TypeError: The `models_as_dict` argument is no longer supported; use a model serializer instead.

**Comment by albertotn** [comment]
same for python 3.12.3

**Comment by danlamanna** [comment]
If you're using `uv` to run this tool, you can use something like `uvx --with 'pydantic<2' -p 3.10 forum-dl ...` to restrict it to using python 3.10 and a version of pydantic before 2.0.
